
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDrightNOTleftPLUSMINUSleftTIMESDIVIDEAND DIVIDE LPAREN MINUS NOT NUMBER OR PLUS RPAREN TIMESexpr : expr OR exprexpr : expr AND exprexpr : NOT exprexpr : aritharith : arith PLUS termarith : arith MINUS termarith : termterm : term TIMES factorterm : term DIVIDE factorterm : factorfactor : LPAREN expr RPARENfactor : NUMBER'
    
_lr_action_items = {'NOT':([0,2,6,8,9,],[2,2,2,2,2,]),'LPAREN':([0,2,6,8,9,11,12,13,14,],[6,6,6,6,6,6,6,6,6,]),'NUMBER':([0,2,6,8,9,11,12,13,14,],[7,7,7,7,7,7,7,7,7,]),'$end':([1,3,4,5,7,10,16,17,18,19,20,21,22,],[0,-4,-7,-10,-12,-3,-1,-2,-5,-6,-8,-9,-11,]),'OR':([1,3,4,5,7,10,15,16,17,18,19,20,21,22,],[8,-4,-7,-10,-12,-3,8,-1,-2,-5,-6,-8,-9,-11,]),'AND':([1,3,4,5,7,10,15,16,17,18,19,20,21,22,],[9,-4,-7,-10,-12,-3,9,9,-2,-5,-6,-8,-9,-11,]),'RPAREN':([3,4,5,7,10,15,16,17,18,19,20,21,22,],[-4,-7,-10,-12,-3,22,-1,-2,-5,-6,-8,-9,-11,]),'PLUS':([3,4,5,7,18,19,20,21,22,],[11,-7,-10,-12,-5,-6,-8,-9,-11,]),'MINUS':([3,4,5,7,18,19,20,21,22,],[12,-7,-10,-12,-5,-6,-8,-9,-11,]),'TIMES':([4,5,7,18,19,20,21,22,],[13,-10,-12,13,13,-8,-9,-11,]),'DIVIDE':([4,5,7,18,19,20,21,22,],[14,-10,-12,14,14,-8,-9,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,2,6,8,9,],[1,10,15,16,17,]),'arith':([0,2,6,8,9,],[3,3,3,3,3,]),'term':([0,2,6,8,9,11,12,],[4,4,4,4,4,18,19,]),'factor':([0,2,6,8,9,11,12,13,14,],[5,5,5,5,5,5,5,20,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr OR expr','expr',3,'p_expr_or','MBLF_HandsOn3-3.py',72),
  ('expr -> expr AND expr','expr',3,'p_expr_and','MBLF_HandsOn3-3.py',76),
  ('expr -> NOT expr','expr',2,'p_expr_not','MBLF_HandsOn3-3.py',80),
  ('expr -> arith','expr',1,'p_expr_arith','MBLF_HandsOn3-3.py',84),
  ('arith -> arith PLUS term','arith',3,'p_arith_plus','MBLF_HandsOn3-3.py',89),
  ('arith -> arith MINUS term','arith',3,'p_arith_minus','MBLF_HandsOn3-3.py',93),
  ('arith -> term','arith',1,'p_arith_term','MBLF_HandsOn3-3.py',97),
  ('term -> term TIMES factor','term',3,'p_term_times','MBLF_HandsOn3-3.py',102),
  ('term -> term DIVIDE factor','term',3,'p_term_divide','MBLF_HandsOn3-3.py',106),
  ('term -> factor','term',1,'p_term_factor','MBLF_HandsOn3-3.py',114),
  ('factor -> LPAREN expr RPAREN','factor',3,'p_factor_expr','MBLF_HandsOn3-3.py',119),
  ('factor -> NUMBER','factor',1,'p_factor_number','MBLF_HandsOn3-3.py',123),
]
